# This is the main build pipeline that verifies and publishes the software
name: Jupyter Test
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the worklow requests
    inputs:
      # Launchpad token required to access collections list
      # token:
      #   type: string
      #   required: true
      #   description: 'Launchpad token's json file name, token required to access the collections'
      #   default: './launchpad_token.json'
      environment:
        type: string
        required: true
        description: 'The environment to run the workflow against'
        default: 'uat'

jobs:
  # First job in the workflow installs and verifies the software
  build:
    name: Test Execution
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Create prerequisites
        run: |
          mkdir tests/jupyter/notebooks/output
      - name: Install dependencies
        run: |
          pip install papermill
      - name: Run Jupyter notebook
        run: |
          python3 "./tests/jupyter/notebook_test.py" -n "./tests/jupyter/notebooks/harmony_concise_api_test.ipynb" -e ${{ github.event.inputs.environment }} -t './launchpad_token.json' -o ./tests/jupyter/notebooks/output
     
