# This is the main build pipeline that verifies and publishes the software
name: Jupyter Test
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # First job in the workflow installs and verifies the software
  build:
    name: Test Execution
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Create prerequisites
        run: |
          mkdir jupyter_notebooks/output
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install papermill
          pip3 install xarray
          pip3 install git+https://github.com/podaac/cmr-association-diff.git@6193079a14e36f4c9526aa426015c2b6be41f0e2
      - name: Run CMR Association diff scripts
        run: |
          cmr_association_diff -e uat -t service -a "./cmr/uat_associations.txt" -p POCLOUD -n \'PODAAC Concise\' -o "./uat_output_json.txt" --token ${{ secrets.LAUNCHPAD_TOKEN_UAT }}
          cmr_association_diff -e ops -t service -a "./cmr/ops_associations.txt" -p POCLOUD -n \'PODAAC Concise\' -o "./ops_output_json.txt" --token ${{ secrets.LAUNCHPAD_TOKEN_OPS }}
      - name: Run Jupyter notebook on UAT
        run: |
          python3 "notebook_test.py" -n "./jupyter_notebooks/harmony_concise_api_test.ipynb" -e uat -i "./uat_output_json.txt" -o "./jupyter_notebooks/output"
      - name: Run Jupyter notebook on OPS
        run: |
          python3 "notebook_test.py" -n "./jupyter_notebooks/harmony_concise_api_test.ipynb" -e ops -i "./ops_output_json.txt" -o "./jupyter_notebooks/output"
